title: microhash
description: A lightweight, portable, non-cryptographic 64-bit hash function.
theme: just-the-docs

url: https://arawn-davies.co.uk
baseurl: /microhash

aux_links:
  "View on GitHub":
    - "https://github.com/Arawn-Davies/microhash"

search_enabled: true
heading_anchors: true
color_scheme: dark
enable_copy_code_button: true
aux_links_new_tab: true
